<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="PlayniteSDK" Version="6.16.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="extension.yaml" CopyToOutputDirectory="Always" />
    <None Update="icon.png" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
