AddonId: ImportAnalyzer
Packages:
  - Version: '0.1'
    RequiredApiVersion: '6.16.0'
    ReleaseDate: '2026-07-29'
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/2026-07-29/ImportAnalyzer_0_1.pext'
    Changelog:
      - "Initial release"
  - Version: '0.2'
    RequiredApiVersion: '6.16.0'
    ReleaseDate: '2026-07-31'
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/importanalyzer0.2/ImportAnalyzer_0_2.pext'
    Changelog:
      - "Tagging games missing from import now also removes the tag from games that aren't missing"
      - "Fixed exception when games with duplicate IDs are imported"
      - "Fixed typos"
  - Version: '0.2.1'
    RequiredApiVersion: '6.16.0'
    ReleaseDate: '2026-07-31'
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/importanalyzer0.2.1/ImportAnalyzer_0_2_1.pext'
    Changelog:
      - "Fixed tagging not doing anything"
  - Version: '0.3.0'
    RequiredApiVersion: '6.16.0'
    ReleaseDate: '{NEWDATE}'
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/{NEWDATE}/ImportAnalyzer_0_3_0.pext'
    Changelog:
      - "Offer to tag specific sources of imported games as missing games too. This hooks into the recent Steam plugin update that will have games in the import just for time played in the past."
      - "Fixed not being able to sort by source."
      - "Fixed complex import plugins from being offered for analysis, when the result would always be empty. At this moment that's only the Humble library plugin."
