AddonId: FilterSearch
Packages:
  - Version: '0.1'
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-20
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-08-20/MetadataSearch_0_1.pext'
    Changelog:
      - 'Initial release'
  - Version: '1.0'
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-09-09
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-09-09/FilterSearch_1.pext'
    Changelog:
      - 'Rename from Metadata Search to Filter Search'
      - 'Added settings'
      - 'Fixed database updates not being reflected in search'
      - 'Added platform icons'
  - Version: '1.0.1'
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-09-11
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-09-09/FilterSearch_1_0_1.pext'
    Changelog:
      - 'Fixed broken settings'
  - Version: '1.1'
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-09-17
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/filtersearch1.1/FilterSearch_1_1.pext'
    Changelog:
      - 'Activating search items now focuses the Playnite window and library view'
      - 'Added global search items to change the filter settings for installed/hidden/favorite/match all filters, and to clear all filters'
      - 'Added search contexts to change the library sorting order and grouping'
  - Version: '1.1.1'
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-10-04
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-10-04/FilterSearch_1_1_1.pext'
    Changelog:
      - 'Fixed library plugins only showing the ones loaded in before the Filter Search plugin was loaded in'
      - 'Fixed some settings not saving'
      - 'Default keyword for the library search context is now "lib"'
