AddonId: ImportAnalyzer
Packages:
  - Version: '0.1'
    RequiredApiVersion: '6.16.0'
    ReleaseDate: '2026-07-29'
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/2026-07-29/ImportAnalyzer_0_1.pext'
    Changelog:
      - "Initial release"
  - Version: '0.2'
    RequiredApiVersion: '6.16.0'
    ReleaseDate: '2026-07-31'
    PackageUrl: 'https://github.com/Jeshibu/PlayniteExtensions/releases/download/importanalyzer0.2/ImportAnalyzer_0_2.pext'
    Changelog:
      - "Tagging games missing from import now also removes the tag from games that aren't missing"
      - "Fixed exception when games with duplicate IDs are imported"
      - "Fixed typos"
