AddonId: ViveportLibrary
Packages:
  - Version: 0.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-10-13
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/viveport0.1/ViveportLibrary_0_1.pext
    Changelog:
     - Initial release
  - Version: 0.1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-11-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2022-11-23/ViveportLibrary_0_1_1.pext
    Changelog:
     - Fixed missing icon in "Update Game Library" menu
  - Version: 0.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-11-26
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/viveport0.2/ViveportLibrary_0_2.pext
    Changelog:
     - Added option to tag Viveport Infinity games
     - Fixed error when parsing malformed files (contributed by SparrowBrain)
  - Version: 0.2.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-12-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/viveport0.2.1/ViveportLibrary_0_2_1.pext
    Changelog:
     - Fixed error when metadata existed twice in Viveport files
  - Version: 0.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-27
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/viveport0.3/ViveportLibrary_0_3.pext
    Changelog:
     - Added metadata provider
  - Version: 0.3.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-03-11
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-03-11/ViveportLibrary_0_3_1.pext
    Changelog:
     - Fixed empty collection values not allowing fallback to other metadata providers
  - Version: 0.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2025-03-29
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-03-29/ViveportLibrary_0_4.pext
    Changelog:
     - Made Viveport Infinity a separate source
     - Added a main menu > Extensions > Viveport entry to reset sources for already imported Viveport games
  - Version: 0.4.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2025-08-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-08-16/ViveportLibrary_0_4_1.pext
    Changelog:
     - Fixed metadata collection failing
  - Version: 0.4.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: {NEWDATE}
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/{NEWDATE}/ViveportLibrary_0_4_2.pext
    Changelog:
     - "Fixed platform matching failing to match some platforms if they'd been renamed"
