AddonId: LaunchBoxMetadata
Packages:
  - Version: 0.1.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-02-26
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/launchbox0.1.1/LaunchBoxMetadata_0_1_1.pext
    Changelog:
      - Added line breaks to description
      - Removed company forms from developers/publishers
      - Fixed hyperlink in settings
  - Version: 0.2
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-03-04
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/launchbox0.2/LaunchBoxMetadata_0_2.pext
    Changelog:
      - Automated download and database initialization process (manual process is still available)
      - Added settings for what image types (and minimum sizes) to use for covers and backgrounds
      - Wikipedia and video links can now optionally be added to games
      - Images will now be scaled down if they exceed user-specified width and height
      - Fixed games sometimes appearing twice in the search results with the same name
  - Version: 0.2.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-03-06
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/launchbox0.2.1/LaunchBoxMetadata_0_2_1.pext
    Changelog:
      - Fixed settings being broken for users who did not have DuplicateHider extension installed
  - Version: 0.3
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-03-07
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/launchbox0.3/LaunchBoxMetadata_0_3.pext
    Changelog:
      - Now using thumbnails for image selection and filtering. This greatly improves metadata collection speed when images are involved.
      - Fixed links not allowing fallback on other metadata providers
  - Version: 0.4
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-04-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-16/LaunchBoxMetadata_0_4.pext
    Changelog:
      - Added option to use LaunchBox images as icons (Clear Logos only by default)
      - Made platform name matching for background downloads more permissive (ignoring non-letter and non-digit characters)
  - Version: 0.5
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-04-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-18/LaunchBoxMetadata_0_5.pext
    Changelog:
      - Added option to extend any image to square (useful for icons)
  - Version: 0.5.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-04-20
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/launchbox0.5.1/LaunchBoxMetadata_0_5_1.pext
    Changelog:
      - Fixed database import failing silently (due to recent data with missing field)
      - Fixed manual data import not reporting progress
  - Version: 0.6
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-04-23
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-04-23/LaunchBoxMetadata_0_6.pext
    Changelog:
      - Fixed image fetching for games with special characters in their name (like &)
      - Added settings to disable and prioritize image regions
  - Version: 0.6.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-05-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-05-16/LaunchBoxMetadata_0_6_1.pext
    Changelog:
      - Small platform matching improvements
  - Version: 0.6.2
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2023-07-26
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2023-07-26/LaunchBoxMetadata_0_6_2.pext
    Changelog:
      - Small game matching improvements
  - Version: 0.6.3
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-01-10
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-01-10/LaunchBoxMetadata_0_6_3.pext
    Changelog:
      - Fixed database import process choking on broken data
  - Version: 0.6.4
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-01-31
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-01-31/LaunchBoxMetadata_0_6_4.pext
    Changelog:
      - Fixed image fetching
  - Version: 0.7
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-06-22
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-06-22/LaunchBoxMetadata_0_7.pext
    Changelog:
      - Split developers and publishers into separate entries when there are multiple
  - Version: 0.7.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-08-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-08-08/LaunchBoxMetadata_0_7_1.pext
    Changelog:
      - Lists in settings no longer block mousewheel scrolling when the cursor is on them
      - Improvement in connection handling; less likely to run out of connections
  - Version: 0.7.2
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-08-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-08-08/LaunchBoxMetadata_0_7_2.pext
    Changelog:
      - Fixed image downloads
  - Version: 0.7.3
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-08-08
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-08-08/LaunchBoxMetadata_0_7_3.pext
    Changelog:
      - Fixed scrolling on regions list in the settings
  - Version: 0.7.4
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2024-12-18
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2024-08-08/LaunchBoxMetadata_0_7_4.pext
    Changelog:
      - Fixed database creation failing due to illegal XML character
  - Version: 0.7.5
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2025-07-25
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/launchbox0.7.5/LaunchBoxMetadata_0_7_5.pext
    Changelog:
      - Fixed no images being found
      - Shortened link name from LaunchBox Games Database to just LaunchBox
  - Version: 0.8
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2025-08-16
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-08-16/LaunchBoxMetadata_0_8.pext
    Changelog:
      - "New database format that requires redownloading database. It is smaller and faster to create."
      - "Added setting to notify you after x days since last database update to update it again."
      - "Added Icon image source type as default enabled for the icon field."
      - "All checks regarding database existence and age now run at both startup and when fetching metadata."
  - Version: 0.8.1
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2025-08-20
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-08-20/LaunchBoxMetadata_0_8_1.pext
    Changelog:
      - "Fixed platform matching failing to match some platforms if they'd been renamed."
      - "Fixed DLL conflict with Extra Metadata Loader. Probably still conflicts with Description Image Fixer."
  - Version: "0.9"
    RequiredApiVersion: 6.8.0
    ReleaseDate: 2025-09-09
    PackageUrl: https://github.com/Jeshibu/PlayniteExtensions/releases/download/2025-09-09/LaunchBoxMetadata_0_9.pext
    Changelog:
      - "Updated Magick.NET dependency to the same version as Description Image Fixer."
      - "⚠ Likely conflicts with Extra Metadata Loader until it updates its Magick.NET."
      - "⚠ This update will once again require you to re-initialize the database."
      - "New: import genres to your games. Optionally add Wikipedia and/or video links."
      - "Fix: PC-98 games would not match platforms not named exactly PC-9801."
